### ISSUE TITLE
g++-8 is not present in Ubuntu 16.04 repos

### ISSUE THREAD

**Issue by marcus7070** [CadQuery/OCP#21]
I'm trying to recreate the environment and build process from the various yaml files (in order to package it in Nix) and I'm getting confused.

The `build-bindings-job.yml` contains:
```yaml
parameters:
  vmImage: 'Ubuntu-16.04'
  CXX: g++-8
jobs:
- job: ${{ parameters.name }}
  - ${{ if contains(parameters.vmImage, 'Ubuntu') }}:
    - bash: sudo apt-get install ${{ parameters.CXX }} mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev
...
    - ${{ if contains(parameters.vmImage, 'Ubuntu') }}:
      - bash: |
          source activate cpp-py-bindgen && \
          cmake -B build -S "../$(OCP_src)" -G Ninja -DCMAKE_BUILD_TYPE=Release && \
          cmake --build build -j $(n_cores) -- -k 0 && \
          rm -rf build/CMakeFiles
        displayName: 'Compile'
        env:
          CXX: ${{ parameters.CXX }}
```
The Ubuntu 16.04 repo does not contain g++-8: https://packages.ubuntu.com/search?keywords=g%2B%2B-8
Running `sudo apt-get install g++-8` in a fresh Ubuntu 16.04 server results in some combination of gcc5 and clang-8. Here is a screenshot of the apt log.
![screenshot2020-06-10-110743](https://user-images.githubusercontent.com/50230945/84217286-e2201f00-ab0a-11ea-95b8-4c0d472cd93c.png)

I don't know how to get the exact Ubuntu-16.04 image the Azure pipeline uses so I don't know if it's got updated repos or something funny. I'm also not very experienced with c++ compilers. Is OCP intended to to be compiled with clang-8 or gcc8?
